#!/bin/bash -exu

set -o pipefail

RUN_DIR=/var/vcap/sys/run/director-bosh-dns
DNS_DIR=/var/vcap/instance/dns
PIDFILE=$RUN_DIR/director-bosh-dns.pid
LOG_DIR=/var/vcap/sys/log/director-bosh-dns
JOB_DIR=/var/vcap/jobs/director-bosh-dns
DNS_PACKAGE=/var/vcap/packages/director-bosh-dns
SCRIPT_NAME=ctl

function start_logging() {
  exec > >(prepend_datetime >> $LOG_DIR/${SCRIPT_NAME}.stdout.log)
  exec 2> >(prepend_datetime >> $LOG_DIR/${SCRIPT_NAME}.stderr.log)
}

function prepend_datetime() {
  awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
}

function pid_exists() {
  ps -p $1 &> /dev/null
}

function create_directories_and_chown_to_vcap() {
  mkdir -p "${LOG_DIR}"
  chown -R vcap:vcap "${LOG_DIR}"

  mkdir -p "${RUN_DIR}"
  chown -R vcap:vcap "${RUN_DIR}"

  mkdir -p "${DNS_DIR}"
  touch "${DNS_DIR}/records.json"
  chown -R vcap:vcap "${DNS_DIR}"
}

function start_dns() {
  if [ -e "$PIDFILE" ]; then
    pid=$(head -1 "${PIDFILE}")
    if pid_exists "$pid"; then
      return 0
    fi
  fi

  chpst -u vcap:vcap \
    "${DNS_PACKAGE}/bin/director-bosh-dns" \
    1>> ${LOG_DIR}/director_bosh_dns.stdout.log \
    2>> ${LOG_DIR}/director_bosh_dns.stderr.log &

  echo $! > $PIDFILE
}

function stop_dns() {
  local pid

  if [ -e $PIDFILE ]
  then
    pid=$(head -1 $PIDFILE)
  else
    exit 0
  fi

  if [ ! -z $pid ] && pid_exists $pid
  then
    set +e
    kill -15 $pid
    set -e
  fi

  if [ -e /proc/$pid ]
  then
    set +e
    kill -9 $pid
    set -e
  fi

  rm -f $PIDFILE
}

function main() {
  create_directories_and_chown_to_vcap
  start_logging

  case ${1} in
    start)
      start_dns
      ;;

    stop)
      stop_dns
      ;;

    *)
      echo "Usage: ${0} {start|stop}"
      ;;
  esac
}

main $@
