#!/bin/bash -exu

DNS_DIR=/var/vcap/instance/dns
RECORDS_FILE="${DNS_DIR}/records.json"

if [ ! -d "${DNS_DIR}" ]; then
  mkdir -p "${DNS_DIR}"
fi

if [ ! -f "${RECORDS_FILE}" ]; then
    touch "${RECORDS_FILE}"
fi

chown root:vcap "${RECORDS_FILE}"
chmod 660 "${RECORDS_FILE}"
