#!/bin/bash -e

export GO111MODULE=on
export GOPATH=${PWD}/gopath
export GOCACHE=${PWD}/go-build
export GOFLAGS=-mod=vendor

export PATH=${PATH}:${GOPATH}/bin

go get github.com/onsi/ginkgo/ginkgo

pushd git/src/director-bosh-dns
ginkgo ./... 


