name: director-bosh-dns

releases:
- name: director-bosh-dns
  sha1: a365141b2204233fca76c6d97ca85ff6805e2b33
  url: https://github.com/starkandwayne/director-bosh-dns-boshrelease/releases/download/v0.1.0/director-bosh-dns-0.1.0.tgz
  version: 0.1.0
- name: bosh
  sha1: b43850fadb8930c945c7107d47adff55abc202ea
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=268.4.0
  version: 268.4.0
- name: bpm
  sha1: 42b95d4a0d6d15dd0b0ead62418ffb56208e2307
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.0
  version: 1.0.0
