---
meta:
  name: director-bosh-dns-release
  target: pipes@main
  url: https://pipes.starkandwayne.com

  test-errand: ~

  initial_version: 0.1.0

  git:
    email: drnic+bot@starkandwayne.com
    name: Stark & Wayne CI Bot

  bosh-lite:
    target:   10.128.4.73
    cacert:   ((thunder-dome.ca-certificate))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))

  github:
    owner:  starkandwayne
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))
